name: smalldisco
channels:
  - bioconda
  - conda-forge
dependencies:
  - numpy=1.21.0
  - pandas=1.2.5
  - pip
  - python=3.9
  - snakemake=7.19.1
  - click=8.1.3
  - bedtools=2.29.2
  - samtools=1.11
